name: Push docker image

on:  
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@master

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: smarterservers
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: "smarterservers/minecraft-java-server-monitor:v${GITHUB_REF#refs/*/}"